apiVersion: v1
clusters:
  - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYmlDbHZwYVVQdXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBM01URXhNalV4TkRCYUZ3MHpOREEzTURreE1qVTJOREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNoYXoycVo1OVc1REhOdlQ3RzlqRkU5WVZZeXVIZ0YrZXZOZWIwdnlxaHJydHNUTE83UFVnRThydVoKZ2NFUmZSc2ttQ2dwVFRTYnRpU3BXeUNDbVd4dGhPUW53SzNMYllSZ2dRWmFjTkRmdUQxUE1oVjcweEN3bWtneApvUHlpMUg2dWVPVDhrYzZRSm1EYVdCUFpGZmg5bXRkb3FxNjU0RURiOUt1bjE4S1ZqVVRsVVJTa0FYSVFmaEEzCkpZQUZERDZpcVVOdVJpN1IyREZ6WTZIRlVicTQxYXlSMEhBaHlUZDBtZFFGSmFaT283THUwY1UvUkg2KzNrekQKUk84c1pHWktHUWY1dzQ1bUg3YnU5TXJYRDlFOWdsOGxmSnZBUi9naFFFRmJTWE9JM0piaHZ6K2pKMFh0NE9maApBeWhkY2xKMS9FYkJaQ0pJeHFhbkgwY2hMZFQ5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSdXlwL1VQU01PQmJ3Yi9SUm9pYzBmbHdSUmN6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXVaVFA5dStOcQpBei83b1hwQ2IvM3U2SExzRnpJR1ZldVQ5aGFXUXdvQ0d6blZPdm9iVUk1VHVOSVhYZDI3T09STnpmMUlrMjcwCmEydHhGRnd1VW95NG9idGYyc3BGd3dPbG5nRytpZHlld0ZIdm1NeWdvdGF3eFJhRkVuN3VEc0V2WFg3eWlxU1AKVHpFOWFIUG1uMjdCNFRoTDlFaEwyYmZuaEczRXByOEZCNTZZSWx0RmtzTW9xVk9uTlF2aG0xaEZyM01neUFqWgpsQzBhYXlpZWpPV1JWZlBIblJFRXpZa3NXU2ZSc0ZiVEVmN0hPTmNVc0lKMHZxSElZM01KVjIxRmdrbm1VYkJ0CnNwbFFpNVIyR2NKNi94aW9heEtabnJOWGltREZNc3d2Q2puT1dEcThiblR1ZnRZemIvQSsyS2lzelJPSjRPWWoKeW5uZllMc0VGZGprCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://BF58DAA0392B4D74808499480B7DD19F.sk1.us-east-1.eks.amazonaws.com
    name: eks-mundos-e.us-east-1.eksctl.io
contexts:
  - context:
        cluster: eks-mundos-e.us-east-1.eksctl.io
        user: i-017e37d9d3557eb06@eks-mundos-e.us-east-1.eksctl.io
    name: i-017e37d9d3557eb06@eks-mundos-e.us-east-1.eksctl.io
current-context: i-017e37d9d3557eb06@eks-mundos-e.us-east-1.eksctl.io
kind: Config
preferences: {}
users:
  - name: i-017e37d9d3557eb06@eks-mundos-e.us-east-1.eksctl.io
    user:
        exec:
            apiVersion: client.authentication.k8s.io/v1beta1
            args:
              - eks
              - get-token
              - --output
              - json
              - --cluster-name
              - eks-mundos-e
              - --region
              - us-east-1
            command: aws
            env:
              - name: AWS_STS_REGIONAL_ENDPOINTS
                value: regional
            interactiveMode: IfAvailable
            provideClusterInfo: false
